import React, { useState, useEffect } from "react";
import {
  Alert,
  ImageBackground,
  Modal,
  ScrollView,
  Pressable,
  Text,
  TextInput,
  View,
} from "react-native";
import styles from "../../assets/styles/routine.styles";
import BubbleBackground from "../../components/BubbleBackground";
import { API_URL, fetchWithTimeout } from "../../constants/api";
import { useAuthStore } from "../../store/authStore";
import * as WebBrowser from "expo-web-browser";

export default function RoutineGeneratorScreen() {
  const [tasks, setTasks] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isLoadingRoutines, setIsLoadingRoutines] = useState(false);
  const [generatedRoutine, setGeneratedRoutine] = useState(null);
  const [generatedRoutineText, setGeneratedRoutineText] = useState("");
  const [savedRoutines, setSavedRoutines] = useState([]);
  const [showSavedModal, setShowSavedModal] = useState(false);
  const [imageLoaded, setImageLoaded] = useState(false);

  const [isCalendarConnected, setIsCalendarConnected] = useState(false);
  const [isSyncingCalendar, setIsSyncingCalendar] = useState(false);

  const [showCustomEventModal, setShowCustomEventModal] = useState(false);
  const [customEventTitle, setCustomEventTitle] = useState("");
  const [customEventDate, setCustomEventDate] = useState(new Date().toISOString().slice(0, 10));
  const [customEventStartTime, setCustomEventStartTime] = useState("13:00");
  const [customEventEndTime, setCustomEventEndTime] = useState("14:00");

  const { token } = useAuthStore();

  useEffect(() => {
    if (token) {
      checkCalendarStatus();
    }
  }, [token]);

  const checkCalendarStatus = async () => {
    try {
      const response = await fetchWithTimeout(`${API_URL}/calendar/status`, {
        headers: getAuthHeaders(),
      });
      const data = await response.json();
      if (response.ok) {
        setIsCalendarConnected(data.connected);
      }
    } catch (error) {
      console.log("Could not fetch calendar status", error);
    }
  };

  const connectGoogleCalendar = async () => {
    try {
      const response = await fetchWithTimeout(`${API_URL}/calendar/auth`, {
        headers: getAuthHeaders(),
      });
      const data = await response.json();
      if (response.ok && data.url) {
        await WebBrowser.openAuthSessionAsync(data.url);
        // After browser closes, check status again
        checkCalendarStatus();
      } else {
        Alert.alert("Connection Failed", "Could not get authorization URL.");
      }
    } catch (error) {
      Alert.alert("Error", "Could not connect to Google Calendar.");
    }
  };

  const parseTime = (timeStr, dateStr) => {
    const match = timeStr.match(/(\d{1,2})[.:](\d{2})\s*(AM|PM|am|pm)?/);
    if (!match) {
        // Fallback for just "8 AM" or "10"
        const fallbackMatch = timeStr.match(/(\d{1,2})\s*(AM|PM|am|pm)?/);
        if (!fallbackMatch) return null;
        let h = parseInt(fallbackMatch[1], 10);
        let m = "00";
        let mod = fallbackMatch[2] ? fallbackMatch[2].toUpperCase() : null;
        if (mod === 'PM' && h < 12) h += 12;
        if (mod === 'AM' && h === 12) h = 0;
        return `${dateStr}T${h.toString().padStart(2, '0')}:${m}:00`;
    }
    
    let hours = parseInt(match[1], 10);
    const minutes = match[2];
    const modifier = match[3] ? match[3].toUpperCase() : null;
    
    if (modifier === 'PM' && hours < 12) hours += 12;
    if (modifier === 'AM' && hours === 12) hours = 0;
    
    const formattedHours = hours.toString().padStart(2, '0');
    return `${dateStr}T${formattedHours}:${minutes}:00`;
  };

  const syncRoutineToCalendar = async () => {
    if (!generatedRoutine || !generatedRoutine.blocks) {
      Alert.alert("Missing Routine", "No routine to sync.");
      return;
    }

    setIsSyncingCalendar(true);

    try {
      const dateStr = new Date().toISOString().slice(0, 10);
      
      let successCount = 0;
      // Get the local timezone safely (fallback to UTC if it fails on older devices)
      let tz = "UTC";
      try { tz = Intl.DateTimeFormat().resolvedOptions().timeZone; } catch (e) {}

      for (const block of generatedRoutine.blocks) {
          const startTime = parseTime(block.start, dateStr);
          const endTime = parseTime(block.end, dateStr);
          
          if (!startTime || !endTime) {
            console.log("Skipping invalid block time:", block.start, block.end);
            continue;
          }
          
          const res = await fetchWithTimeout(`${API_URL}/calendar/events`, {
              method: "POST",
              headers: getAuthHeaders(),
              body: JSON.stringify({
                  eventDetails: {
                      summary: block.activity,
                      description: "Generated by CareWave Routine Planner",
                      start: { dateTime: startTime, timeZone: tz },
                      end: { dateTime: endTime, timeZone: tz }
                  }
              })
          });
          
          if (res.ok) {
            successCount++;
          } else {
            console.error("Failed to sync block", await res.text());
          }
      }

      Alert.alert("Success", `Synced ${successCount} activities to your Google Calendar!`);
    } catch (error) {
      Alert.alert("Sync Failed", "Could not sync all events to Google Calendar.");
    } finally {
      setIsSyncingCalendar(false);
    }
  };

  const syncSingleBlockToCalendar = async (block) => {
    try {
      const dateStr = new Date().toISOString().slice(0, 10);
      let tz = "UTC";
      try { tz = Intl.DateTimeFormat().resolvedOptions().timeZone; } catch (e) {}

      const startTime = parseTime(block.start, dateStr);
      const endTime = parseTime(block.end, dateStr);

      if (!startTime || !endTime) {
        Alert.alert("Invalid Time", "The generated time format could not be parsed.");
        return;
      }

      const res = await fetchWithTimeout(`${API_URL}/calendar/events`, {
          method: "POST",
          headers: getAuthHeaders(),
          body: JSON.stringify({
              eventDetails: {
                  summary: block.activity,
                  description: "Generated by CareWave Routine Planner",
                  start: { dateTime: startTime, timeZone: tz },
                  end: { dateTime: endTime, timeZone: tz }
              }
          })
      });

      if (res.ok) {
        Alert.alert("Success", `Added "${block.activity}" to your Google Calendar!`);
      } else {
        throw new Error("Failed to add event");
      }
    } catch (error) {
      Alert.alert("Sync Failed", "Could not sync the event to Google Calendar.");
    }
  };

  const handleCreateCustomEvent = async () => {
    if (!customEventTitle.trim() || !customEventStartTime || !customEventEndTime) {
      Alert.alert("Missing Fields", "Please fill in all fields.");
      return;
    }

    try {
      const dateStr = customEventDate || new Date().toISOString().slice(0, 10);
      let tz = "UTC";
      try { tz = Intl.DateTimeFormat().resolvedOptions().timeZone; } catch (e) {}

      const startTime = parseTime(customEventStartTime, dateStr);
      const endTime = parseTime(customEventEndTime, dateStr);

      if (!startTime || !endTime) {
        Alert.alert("Invalid Time", "Please use HH:MM format like 14:00 or 2:00 PM");
        return;
      }

      const res = await fetchWithTimeout(`${API_URL}/calendar/events`, {
          method: "POST",
          headers: getAuthHeaders(),
          body: JSON.stringify({
              eventDetails: {
                  summary: customEventTitle,
                  description: "Custom event from CareWave",
                  start: { dateTime: startTime, timeZone: tz },
                  end: { dateTime: endTime, timeZone: tz }
              }
          })
      });

      if (res.ok) {
        Alert.alert("Success", `Added "${customEventTitle}" to your Calendar!`);
        setShowCustomEventModal(false);
        setCustomEventTitle("");
      } else {
        throw new Error("Failed to create event");
      }
    } catch (error) {
      Alert.alert("Failed", "Could not create custom event.");
    }
  };

  const formatTimetableForAlert = (timetable) => {
    if (!timetable) return "No timetable was returned by the server.";

    if (Array.isArray(timetable.blocks) && timetable.blocks.length > 0) {
      const lines = timetable.blocks.map(
        (block) => `${block.start} - ${block.end}: ${block.activity}`
      );

      if (timetable.summary) {
        lines.push(`\nSummary: ${timetable.summary}`);
      }

      return lines.join("\n");
    }

    if (timetable.raw_text) {
      return timetable.raw_text;
    }

    return JSON.stringify(timetable, null, 2);
  };

  const getAuthHeaders = () => {
    if (!token) {
      throw new Error("Please log in first to use saved routines.");
    }

    return {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    };
  };

  const loadSavedRoutines = async (openModal = true) => {
    if (!token) {
      Alert.alert("Login required", "Please log in to view or save routines.");
      return;
    }

    setIsLoadingRoutines(true);

    try {
      const response = await fetchWithTimeout(`${API_URL}/routine`, {
        headers: getAuthHeaders(),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.message || "Failed to load routines");
      }

      setSavedRoutines(data.routines || []);

      if (openModal) {
        setShowSavedModal(true);
      }
    } catch (error) {
      Alert.alert("Could not load routines", error.message || "Try again later.");
    } finally {
      setIsLoadingRoutines(false);
    }
  };

  const saveRoutineToServer = async () => {
    if (!generatedRoutine) {
      Alert.alert("Missing routine", "Generate a routine first.");
      return;
    }

    if (!token) {
      Alert.alert("Login required", "Please log in before saving routines.");
      return;
    }

    setIsSaving(true);

    try {
      const response = await fetchWithTimeout(`${API_URL}/routine/save`, {
        method: "POST",
        headers: getAuthHeaders(),
        body: JSON.stringify({
          title: "Generated routine",
          date: new Date().toISOString().slice(0, 10),
          summary: generatedRoutine.summary || "",
          alertText: generatedRoutineText,
          rawText: tasks.trim(),
          timetable: generatedRoutine,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.message || "Failed to save routine");
      }

      setSavedRoutines((current) => [data.routine, ...current]);
      Alert.alert("Saved", "Routine saved to your profile.");
    } catch (error) {
      Alert.alert("Save failed", error.message || "Could not save routine.");
    } finally {
      setIsSaving(false);
    }
  };

  const deleteRoutineOnServer = async (routineId) => {
    try {
      const response = await fetchWithTimeout(`${API_URL}/routine/${routineId}`, {
        method: "DELETE",
        headers: getAuthHeaders(),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.message || "Failed to delete routine");
      }

      setSavedRoutines((current) => current.filter((routine) => routine._id !== routineId));
      Alert.alert("Deleted", "Routine removed.");
    } catch (error) {
      Alert.alert("Delete failed", error.message || "Could not delete routine.");
    }
  };

  const handleGenerateRoutine = async () => {
    if (!tasks.trim()) {
      Alert.alert("Missing tasks", "Please enter your daily tasks first.");
      return;
    }

    setIsGenerating(true);

    try {
      const response = await fetchWithTimeout(
        `${API_URL}/schedule/parse`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ text: tasks.trim() }),
        },
        25000
      );

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate routine");
      }

      const routineText = formatTimetableForAlert(data.timetable);
      setGeneratedRoutine(data.timetable);
      setGeneratedRoutineText(routineText);
    } catch (error) {
      Alert.alert(
        "Generation Failed",
        error.message || "Could not connect to the timetable generator server."
      );
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <View style={styles.container}>
      <BubbleBackground />
      
      {!isCalendarConnected ? (
        <Pressable
          style={styles.googleCalendarButton}
          onPress={connectGoogleCalendar}
        >
          <Text style={styles.googleCalendarButtonText}>🗓 Connect Calendar</Text>
        </Pressable>
      ) : (
        <View style={styles.googleCalendarConnected}>
          <Text style={styles.googleCalendarConnectedText}>✅ Connected</Text>
        </View>
      )}

      <ImageBackground
        source={require("../../assets/images/routine-generator-reference.png")}
        style={styles.cardBackground}
        imageStyle={styles.cardImage}
        resizeMode="contain"
        onLoad={() => setImageLoaded(true)}
      >
        <View style={[styles.overlayLayer, { opacity: imageLoaded ? 1 : 0 }]}>
          <TextInput
            style={styles.input}
            placeholder="Describe your daily tasks to generate a routine..."
            placeholderTextColor="#7AA7D6"
            multiline
            textAlignVertical="top"
            value={tasks}
            onChangeText={setTasks}
          />

          <Pressable
            style={[styles.enterButton, isGenerating && styles.enterButtonDisabled]}
            onPress={handleGenerateRoutine}
            disabled={isGenerating}
          >
            <Text style={styles.enterButtonText}>
              {isGenerating ? "Generating..." : "Generate Routine"}
            </Text>
          </Pressable>

          <View style={styles.actionColumn}>
            <Pressable
              style={[
                styles.secondaryButton,
                isLoadingRoutines && styles.buttonDisabled,
              ]}
              onPress={() => loadSavedRoutines(true)}
              disabled={isLoadingRoutines}
            >
              <Text style={styles.secondaryButtonText}>
                {isLoadingRoutines ? "Loading..." : "View Saved Routines"}
              </Text>
            </Pressable>
          </View>

          <Modal
            visible={showCustomEventModal}
            animationType="slide"
            transparent
            onRequestClose={() => setShowCustomEventModal(false)}
          >
            <View style={styles.modalBackdrop}>
              <View style={styles.modalCard}>
                <Text style={styles.modalTitle}>New Calendar Event</Text>
                
                <TextInput
                  style={[styles.modalInput, { marginBottom: 15, minHeight: 40 }]}
                  placeholder="Event Title (e.g. Doctor Appt)"
                  placeholderTextColor="#7AA7D6"
                  value={customEventTitle}
                  onChangeText={setCustomEventTitle}
                />

                <Text style={{ color: '#244F82', marginBottom: 5, fontWeight: 'bold' }}>Date (YYYY-MM-DD)</Text>
                <TextInput
                  style={[styles.modalInput, { marginBottom: 15, minHeight: 40 }]}
                  placeholder="e.g. 2026-10-31"
                  placeholderTextColor="#7AA7D6"
                  value={customEventDate}
                  onChangeText={setCustomEventDate}
                />

                <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 }}>
                  <View style={{ flex: 1, marginRight: 5 }}>
                    <Text style={{ color: '#244F82', marginBottom: 5, fontWeight: 'bold' }}>Start (HH:MM)</Text>
                    <TextInput
                      style={[styles.modalInput, { minHeight: 40 }]}
                      placeholder="e.g. 09:00"
                      placeholderTextColor="#7AA7D6"
                      value={customEventStartTime}
                      onChangeText={setCustomEventStartTime}
                    />
                  </View>
                  <View style={{ flex: 1, marginLeft: 5 }}>
                    <Text style={{ color: '#244F82', marginBottom: 5, fontWeight: 'bold' }}>End (HH:MM)</Text>
                    <TextInput
                      style={[styles.modalInput, { minHeight: 40 }]}
                      placeholder="e.g. 10:00"
                      placeholderTextColor="#7AA7D6"
                      value={customEventEndTime}
                      onChangeText={setCustomEventEndTime}
                    />
                  </View>
                </View>

                <Pressable
                  style={[styles.syncCalendarButton, { marginBottom: 15 }]}
                  onPress={handleCreateCustomEvent}
                >
                  <Text style={styles.syncCalendarButtonText}>Add to Google Calendar</Text>
                </Pressable>

                <Pressable
                  style={styles.closeButton}
                  onPress={() => setShowCustomEventModal(false)}
                >
                  <Text style={styles.closeButtonText}>Cancel</Text>
                </Pressable>
              </View>
            </View>
          </Modal>

          <Modal
            visible={!!generatedRoutine}
            animationType="slide"
            transparent
            onRequestClose={() => setGeneratedRoutine(null)}
          >
            <View style={styles.modalBackdrop}>
              <View style={styles.generatedRoutineModal}>
                <Text style={styles.generatedRoutineModalTitle}>Generated Routine</Text>
                <ScrollView style={styles.generatedRoutineModalContent}>
                  {generatedRoutine?.blocks && generatedRoutine.blocks.length > 0 ? (
                    generatedRoutine.blocks.map((block, i) => (
                      <View key={i} style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 10, backgroundColor: '#FFFFFF', padding: 10, borderRadius: 8, borderWidth: 1, borderColor: '#D0E3F5' }}>
                        <View style={{ flex: 1 }}>
                          <Text style={{ fontWeight: 'bold', color: '#244F82', fontSize: 13 }}>{block.start} - {block.end}</Text>
                          <Text style={{ color: '#346EAF', fontSize: 14 }}>{block.activity}</Text>
                        </View>
                        {isCalendarConnected && (
                          <Pressable
                            style={{ backgroundColor: '#E6F4EA', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 16, borderWidth: 1, borderColor: '#137333' }}
                            onPress={() => syncSingleBlockToCalendar(block)}
                          >
                            <Text style={{ color: '#137333', fontSize: 12, fontWeight: 'bold' }}>🗓 Sync</Text>
                          </Pressable>
                        )}
                      </View>
                    ))
                  ) : (
                    <Text style={styles.generatedRoutineModalText}>{generatedRoutineText}</Text>
                  )}
                </ScrollView>
                <Pressable
                  style={[
                    styles.saveFromModalButton,
                    (isSaving || !token) && styles.buttonDisabled,
                  ]}
                  onPress={saveRoutineToServer}
                  disabled={isSaving || !token}
                >
                  <Text style={styles.saveFromModalButtonText}>
                    {isSaving ? "Saving..." : "Save Routine to CareWave"}
                  </Text>
                </Pressable>

                {isCalendarConnected && (
                  <Pressable
                    style={[
                      styles.syncCalendarButton,
                      isSyncingCalendar && styles.buttonDisabled,
                    ]}
                    onPress={syncRoutineToCalendar}
                    disabled={isSyncingCalendar}
                  >
                    <Text style={styles.syncCalendarButtonText}>
                      {isSyncingCalendar ? "Syncing All..." : "🗓 Sync ALL to Google Calendar"}
                    </Text>
                  </Pressable>
                )}

                <Pressable
                  style={styles.closeButton}
                  onPress={() => setGeneratedRoutine(null)}
                >
                  <Text style={styles.closeButtonText}>Close</Text>
                </Pressable>
              </View>
            </View>
          </Modal>

          <Modal
            visible={showSavedModal}
            animationType="slide"
            transparent
            onRequestClose={() => setShowSavedModal(false)}
          >
            <View style={styles.modalBackdrop}>
              <View style={styles.modalCard}>
                <Text style={styles.modalTitle}>Saved Routines</Text>
                <ScrollView
                  style={styles.modalList}
                  contentContainerStyle={styles.modalListContent}
                >
                  {savedRoutines.length === 0 ? (
                    <Text style={styles.modalEmptyText}>No saved routines yet.</Text>
                  ) : (
                    savedRoutines.map((routine) => (
                      <View key={routine._id} style={styles.routineItem}>
                        <Text style={styles.routineItemTitle}>
                          {routine.title || "Routine"}
                        </Text>
                        <Text style={styles.routineItemMeta}>
                          {routine.date || "No date"}
                        </Text>
                        <Text style={styles.routineItemText}>
                          {routine.alertText || formatTimetableForAlert(routine)}
                        </Text>
                        <View style={styles.routineItemActions}>
                          <Pressable
                            style={[styles.itemActionButton, styles.deleteActionButton]}
                            onPress={() => deleteRoutineOnServer(routine._id)}
                          >
                            <Text style={styles.itemActionText}>Delete</Text>
                          </Pressable>
                        </View>
                      </View>
                    ))
                  )}
                </ScrollView>
                <Pressable
                  style={styles.closeButton}
                  onPress={() => setShowSavedModal(false)}
                >
                  <Text style={styles.closeButtonText}>Close</Text>
                </Pressable>
              </View>
            </View>
          </Modal>

        </View>
      </ImageBackground>

      {isCalendarConnected && (
        <Pressable
          style={styles.customEventFab}
          onPress={() => setShowCustomEventModal(true)}
        >
          <Text style={styles.syncCalendarButtonText}>
            ➕ Custom Event
          </Text>
        </Pressable>
      )}
    </View>
  );
}
